server:
  port: 80
spring:
  application:
    name: springcloud-feign
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://master:8760/eureka/,http://peer1:8761/eureka/,http://peer2:8762/eureka/
    enabled: true
logging:
  config: classpath:logback.xml
  path: E://spring-cloud/consumer
  file: spring-cloud-consumer.log
  level:
    root: info
feign:
  hystrix:
    enabled: true